FROM golang:1.19.1 AS builder

### Copy Go code
WORKDIR /src/
COPY . .

### Build executables
RUN go build -o /app/webapi ./cmd/webapi

### Create final container
FROM debian:stable

### Inform Docker about which port is used
EXPOSE 3000 4000

### Copy the build executable from the builder image
WORKDIR /app/
VOLUME /app/service/database/source/
COPY --from=builder /app/webapi ./
COPY ./service/database/source /app/service/database/source

### Executable command
CMD ["/app/webapi"]

