### GET Stream
GET http://localhost:3000/user/1/photos/
Content-Type: application/json
Authorization: Bearer 1


### Delete Photo (Funzionate)
DELETE  http://localhost:3000/user/2/photos/4/
Content-Type: application/json
Authorization: Bearer 2

### Like Photo (Funzionate)
PUT http://localhost:3000/user/2/photos/10/likes/1
Content-Type: application/json
Authorization: Bearer 1


### Unlike Photo (Funzionate)
DELETE http://localhost:3000/user/1/photos/8/likes/2
Content-Type: application/json
Authorization: Bearer 2


### Post Comment (Funzionate)
POST http://localhost:3000/user/1/photos/8/comments/
Content-Type: application/json
Authorization: Bearer 2

{
	"comment": "Prova Commento da path 2"
}

### GET Comments of a photo (Funzionate)
GET http://localhost:3000/user/1/photos/8/comments/
Content-Type: application/json
Authorization: Bearer 2


### Get single comment (Funzionate)
GET http://localhost:3000/user/1/photos/8/comments/5
Content-Type: application/json
Authorization: Bearer 2


### Delete single comment
DELETE http://localhost:3000/user/1/photos/8/comments/5
Content-Type: application/json
Authorization: Bearer 2
